apiVersion: v1
kind: Namespace
metadata:
  name: test-env-trigger-creation-project-staging
  labels:
    environmentId: env_f66d801e-eccb-484d-81c8-134751b15433
    projectId: project_3010652f-81eb-435c-b157-074bbab4e211
    projectName: test-env-trigger-creation-project
    environmentName: staging
    organizationId: org_12ab5a69-48a2-42d7-ad36-d59a2bca4805
