apiVersion: v1
kind: Namespace
metadata:
  name: test-env-trigger-creation-project-prod
  labels:
    environmentId: env_1570badf-4ced-4ce4-a308-dec37673227f
    projectId: project_3010652f-81eb-435c-b157-074bbab4e211
    projectName: test-env-trigger-creation-project
    environmentName: prod
    organizationId: org_12ab5a69-48a2-42d7-ad36-d59a2bca4805
